1. What query would you run to get all the countries that speak Slovene? Your query should return the name of the country, language and language percentage. Your query should arrange the result by language percentage in descending order.
SELECT countries.name, languages.language, languages.percentage
FROM countries
JOIN languages ON countries.id = languages.country_id
WHERE languages.language = 'Slovene'
order by languages.percentage desc
2. What query would you run to display the total number of cities for each country? Your query should return the name of the country and the total number of cities. Your query should arrange the result by the number of cities in descending order.
select countries.name, count(cities.name) as cities
from cities
left join countries on cities.country_id
group by countries.name
order by  cities desc
3. What query would you run to get all the cities in Mexico with a population of greater than 500,000? Your query should arrange the result by population in descending order.
select  cities.name,  cities.population
from cities
where  cities.country_code = 'MEX' and population > 500000
order by population desc
4. What query would you run to get all languages in each country with a percentage greater than 89%? Your query should arrange the result by percentage in descending order.
select  countries.name, languages.language, languages.percentage
from languages
left join countries on languages.country_code = countries.code
where languages.percentage > 89
order by percentage desc
5.What query would you run to get all the countries with Surface Area below 501 and Population greater than 100,000?
select countries.name, countries.surface_area, countries.population
from countries
where surface_area < 501 and population > 100000
select countries.name, countries.surface_area, countries.population
from countries
where surface_area < 501 and population > 100000
6. What query would you run to get countries with only Constitutional Monarchy with a capital greater than 200 and a life expectancy greater than 75 years?
SELECT name, government_form, capital, life_expectancy
FROM countries
WHERE government_form = 'Constitutional Monarchy' AND capital > 200 AND life_expectancy >75;
7. What query would you run to get all the cities of Argentina inside the Buenos Aires district and have the population greater than 500, 000? The query should return the Country Name, City Name, District and Population.
SELECT countries.name, cities.name, cities.district, cities.population FROM cities
LEFT JOIN countries on cities.country_code = country_code
WHERE countries.name = "Argentina" AND cities.district = "Buenos Aires"
HAVING population > 500000;
8. What query would you run to summarize the number of countries in each region? The query should display the name of the region and the number of countries. Also, the query should arrange the result by the number of countries in descending order.
SELECT region, count(*) AS countries
FROM countries
GROUP BY region
ORDER BY countries DESC
